server:
  port: ${PORT:10374}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10372/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: order-api
          uri: lb://order-api
          predicates:
            - Path=/order-api/**
          filters:
            - RewritePath=/order-api/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,loggers

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive.DispatcherHandler: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG